// Automatically generated by MockGen. DO NOT EDIT!
// Source: config.go

package engine

import (
  gomock "code.google.com/p/gomock/gomock"
)

// Mock of Config interface
type MockConfig struct {
  ctrl     *gomock.Controller
  recorder *_MockConfigRecorder
}

// Recorder for MockConfig (not exported)
type _MockConfigRecorder struct {
  mock *MockConfig
}

func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
  mock := &MockConfig{ctrl: ctrl}
  mock.recorder = &_MockConfigRecorder{mock}
  return mock
}

func (_m *MockConfig) EXPECT() *_MockConfigRecorder {
  return _m.recorder
}

func (_m *MockConfig) SmtpConfig() (string, string, string) {
  ret := _m.ctrl.Call(_m, "SmtpConfig")
  ret0, _ := ret[0].(string)
  ret1, _ := ret[1].(string)
  ret2, _ := ret[2].(string)
  return ret0, ret1, ret2
}

func (_mr *_MockConfigRecorder) SmtpConfig() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "SmtpConfig")
}

func (_m *MockConfig) DefaultNotifier() (Notifier, error) {
  ret := _m.ctrl.Call(_m, "DefaultNotifier")
  ret0, _ := ret[0].(Notifier)
  ret1, _ := ret[1].(error)
  return ret0, ret1
}

func (_mr *_MockConfigRecorder) DefaultNotifier() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultNotifier")
}

func (_m *MockConfig) DefaultNotificationRecipient() string {
  ret := _m.ctrl.Call(_m, "DefaultNotificationRecipient")
  ret0, _ := ret[0].(string)
  return ret0
}

func (_mr *_MockConfigRecorder) DefaultNotificationRecipient() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultNotificationRecipient")
}

func (_m *MockConfig) LogLevel() string {
  ret := _m.ctrl.Call(_m, "LogLevel")
  ret0, _ := ret[0].(string)
  return ret0
}

func (_mr *_MockConfigRecorder) LogLevel() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "LogLevel")
}

func (_m *MockConfig) Rules() []Rule {
  ret := _m.ctrl.Call(_m, "Rules")
  ret0, _ := ret[0].([]Rule)
  return ret0
}

func (_mr *_MockConfigRecorder) Rules() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "Rules")
}
