// Automatically generated by MockGen. DO NOT EDIT!
// Source: rule.go

package engine

import (
  gomock "code.google.com/p/gomock/gomock"
  time "time"
)

// Mock of Rule interface
type MockRule struct {
  ctrl     *gomock.Controller
  recorder *_MockRuleRecorder
}

// Recorder for MockRule (not exported)
type _MockRuleRecorder struct {
  mock *MockRule
}

func NewMockRule(ctrl *gomock.Controller) *MockRule {
  mock := &MockRule{ctrl: ctrl}
  mock.recorder = &_MockRuleRecorder{mock}
  return mock
}

func (_m *MockRule) EXPECT() *_MockRuleRecorder {
  return _m.recorder
}

func (_m *MockRule) Name() string {
  ret := _m.ctrl.Call(_m, "Name")
  ret0, _ := ret[0].(string)
  return ret0
}

func (_mr *_MockRuleRecorder) Name() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

func (_m *MockRule) TestTriggered() (bool, bool) {
  ret := _m.ctrl.Call(_m, "TestTriggered")
  ret0, _ := ret[0].(bool)
  ret1, _ := ret[1].(bool)
  return ret0, ret1
}

func (_mr *_MockRuleRecorder) TestTriggered() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "TestTriggered")
}

func (_m *MockRule) SetOptions(opts map[string]string) map[string]string {
  ret := _m.ctrl.Call(_m, "SetOptions", opts)
  ret0, _ := ret[0].(map[string]string)
  return ret0
}

func (_mr *_MockRuleRecorder) SetOptions(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "SetOptions", arg0)
}

// Mock of UrlFetchingRule interface
type MockUrlFetchingRule struct {
  ctrl     *gomock.Controller
  recorder *_MockUrlFetchingRuleRecorder
}

// Recorder for MockUrlFetchingRule (not exported)
type _MockUrlFetchingRuleRecorder struct {
  mock *MockUrlFetchingRule
}

func NewMockUrlFetchingRule(ctrl *gomock.Controller) *MockUrlFetchingRule {
  mock := &MockUrlFetchingRule{ctrl: ctrl}
  mock.recorder = &_MockUrlFetchingRuleRecorder{mock}
  return mock
}

func (_m *MockUrlFetchingRule) EXPECT() *_MockUrlFetchingRuleRecorder {
  return _m.recorder
}

func (_m *MockUrlFetchingRule) Name() string {
  ret := _m.ctrl.Call(_m, "Name")
  ret0, _ := ret[0].(string)
  return ret0
}

func (_mr *_MockUrlFetchingRuleRecorder) Name() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

func (_m *MockUrlFetchingRule) TestTriggered() (bool, bool) {
  ret := _m.ctrl.Call(_m, "TestTriggered")
  ret0, _ := ret[0].(bool)
  ret1, _ := ret[1].(bool)
  return ret0, ret1
}

func (_mr *_MockUrlFetchingRuleRecorder) TestTriggered() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "TestTriggered")
}

func (_m *MockUrlFetchingRule) SetOptions(opts map[string]string) map[string]string {
  ret := _m.ctrl.Call(_m, "SetOptions", opts)
  ret0, _ := ret[0].(map[string]string)
  return ret0
}

func (_mr *_MockUrlFetchingRuleRecorder) SetOptions(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "SetOptions", arg0)
}

func (_m *MockUrlFetchingRule) SetUrlFetcher(f UrlFetcher) UrlFetcher {
  ret := _m.ctrl.Call(_m, "SetUrlFetcher", f)
  ret0, _ := ret[0].(UrlFetcher)
  return ret0
}

func (_mr *_MockUrlFetchingRuleRecorder) SetUrlFetcher(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "SetUrlFetcher", arg0)
}

// Mock of PollingRule interface
type MockPollingRule struct {
  ctrl     *gomock.Controller
  recorder *_MockPollingRuleRecorder
}

// Recorder for MockPollingRule (not exported)
type _MockPollingRuleRecorder struct {
  mock *MockPollingRule
}

func NewMockPollingRule(ctrl *gomock.Controller) *MockPollingRule {
  mock := &MockPollingRule{ctrl: ctrl}
  mock.recorder = &_MockPollingRuleRecorder{mock}
  return mock
}

func (_m *MockPollingRule) EXPECT() *_MockPollingRuleRecorder {
  return _m.recorder
}

func (_m *MockPollingRule) Name() string {
  ret := _m.ctrl.Call(_m, "Name")
  ret0, _ := ret[0].(string)
  return ret0
}

func (_mr *_MockPollingRuleRecorder) Name() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

func (_m *MockPollingRule) TestTriggered() (bool, bool) {
  ret := _m.ctrl.Call(_m, "TestTriggered")
  ret0, _ := ret[0].(bool)
  ret1, _ := ret[1].(bool)
  return ret0, ret1
}

func (_mr *_MockPollingRuleRecorder) TestTriggered() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "TestTriggered")
}

func (_m *MockPollingRule) SetOptions(opts map[string]string) map[string]string {
  ret := _m.ctrl.Call(_m, "SetOptions", opts)
  ret0, _ := ret[0].(map[string]string)
  return ret0
}

func (_mr *_MockPollingRuleRecorder) SetOptions(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "SetOptions", arg0)
}

func (_m *MockPollingRule) ShouldPoll(last_update time.Time) bool {
  ret := _m.ctrl.Call(_m, "ShouldPoll", last_update)
  ret0, _ := ret[0].(bool)
  return ret0
}

func (_mr *_MockPollingRuleRecorder) ShouldPoll(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "ShouldPoll", arg0)
}

func (_m *MockPollingRule) LastDeadline() time.Time {
  ret := _m.ctrl.Call(_m, "LastDeadline")
  ret0, _ := ret[0].(time.Time)
  return ret0
}

func (_mr *_MockPollingRuleRecorder) LastDeadline() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "LastDeadline")
}

func (_m *MockPollingRule) NextDeadline() time.Time {
  ret := _m.ctrl.Call(_m, "NextDeadline")
  ret0, _ := ret[0].(time.Time)
  return ret0
}

func (_mr *_MockPollingRuleRecorder) NextDeadline() *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "NextDeadline")
}
