// Automatically generated by MockGen. DO NOT EDIT!
// Source: url_fetcher.go

package engine

import (
  gomock "code.google.com/p/gomock/gomock"
)

// Mock of UrlFetcher interface
type MockUrlFetcher struct {
  ctrl     *gomock.Controller
  recorder *_MockUrlFetcherRecorder
}

// Recorder for MockUrlFetcher (not exported)
type _MockUrlFetcherRecorder struct {
  mock *MockUrlFetcher
}

func NewMockUrlFetcher(ctrl *gomock.Controller) *MockUrlFetcher {
  mock := &MockUrlFetcher{ctrl: ctrl}
  mock.recorder = &_MockUrlFetcherRecorder{mock}
  return mock
}

func (_m *MockUrlFetcher) EXPECT() *_MockUrlFetcherRecorder {
  return _m.recorder
}

func (_m *MockUrlFetcher) Get(url string) (string, error) {
  ret := _m.ctrl.Call(_m, "Get", url)
  ret0, _ := ret[0].(string)
  ret1, _ := ret[1].(error)
  return ret0, ret1
}

func (_mr *_MockUrlFetcherRecorder) Get(arg0 interface{}) *gomock.Call {
  return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}
